### ISSUE TITLE
"Use GPU" not functioning properly

### ISSUE THREAD

**Issue by ceddose** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#1]
Hi there,
I believe that "Use GPU" isn't working properly,
I'm running Python 3.8.5 & OpenCV compiled with CUDA enabled as well as the Drivers and Toolkits needed.

Clicking "Use GPU" does not save the checkmark (is that intended?), and the FPS remains the same, so I believe that it has no effect.

Any tips to get it running with the GPU? It's unusable with 1.6 FPS so I'd love to get this working at a higher frame rate, thank you!

PS: My GPU is a RTX 2060 so it should fit the specs.

**Comment by Tumppi066** [comment]
Hi and thanks for reaching out.
Unfortunatelly I um unable to use my PC for the weekend, but I will look into this on Monday.

For now I suggest that you run these lines of code in python, so that we can verify that torch is working properly.
import torch 
torch.cuda.is_available()

**Comment by ceddose** [comment]
![image](https://user-images.githubusercontent.com/65426123/170823842-8f4e7b3e-63a2-4d6f-939f-9e22715e68a2.png)

Seems to be reporting correctly.

**Comment by Tumppi066** [comment]
Ok then it's most likely an issue with my code. Like I said I will look into it on Monday, I also have an exam on the same day so it might be a little later on in the day.

**Comment by ceddose** [comment]
No rush! Best of luck on your exam and thanks for making your code public :)

**Comment by Tumppi066** [comment]
Ok I found some time to fix the issue and it was a problem with the controller thread. It was running as fast as it could and flooding the main thread. This caused the screenshotting to be extremely slow and basically bricking the program. I corrected this and you should try the new MainFile.py I uploaded. If it still doesn't work then please do tell me, otherwise close the issue.

Also thanks for the good luck, I will definitely need it :D

**Comment by Tumppi066** [comment]
Also yes I haven't implemented the UseGPU toggle to save it's state. 
As a performance comparison I will also leave this here:
GPU : 1070
CPU : i5 9600k
Performance (Culane18, at 833x480)
CPU : ~10fps
GPU : ~30fps

**Comment by ceddose** [comment]
Works brilliantly now!
Getting ~23FPS with my RTX 2060 now.

Thank you very much :)
