### ISSUE TITLE
Python error on 1.10 installer.exe

### ISSUE THREAD

**Issue by xFortzon** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#185]
I installed Python 3.11.8 manually on another drive because my C drive is too full. Then I ran the 1.10 installer.exe and it finds this Python from my system but it still tries to run the Python installer that complains that I don't have the correct version (probably because it can't find it on my C drive).

**Comment by DylDevs** [comment]
This is interesting, it should work just fine.
Could you try opening a CMD window and typing:
`python --version`

(Also, if possible, it would be better if you joined the [ETS2 Lane Assist Discord server](https://discord.gg/DpJpkNpqwD) for support.)

**Comment by xFortzon** [comment]
Solved the problem. The installer still required extra space from C drive for the installation process despite being on another drive. Once I managed to free some space by restarting my PC, the installer ran fine. My guess is it needs like 300-400mb temporarily from C drive.

**Comment by DylDevs** [comment]
Ah, ok.
