### ISSUE TITLE
Installer cannot find file specified. 

### ISSUE THREAD

**Issue by ghost** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#187]
.\installer.exe
Checking for winget...
Opening winget install page...
Traceback (most recent call last):
  File "installer.py", line 146, in <module>
  File "installer.py", line 48, in InstallWinget
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[38212] Failed to execute script 'installer' due to unhandled exception!

**Comment by Tumppi066** [comment]
You will have to install Winget manually, this is happening for some people for some reason.

https://apps.microsoft.com/detail/9NBLGGH4NNS1?rtc=1&hl=en-gb&gl=US#activetab=pivot:overviewtab

**Comment by Tumppi066** [comment]
I will be making a new installer that does everything, though it might take a while.

**Comment by StochasticSanity** [comment]
@Tumppi066   Microsoft anti-competitive practices of pre-installed apps and and a pre-installed store are not universally true on all versions of windows, so this should instead use a downloadable binary or other method. 

They were already sued for this practice for including Microsoft Internet Explorer in the past, though the current pro-monopoly climate had not done anything about their current practice, it should still be discouraged by developers.

**Comment by Tumppi066** [comment]
Thx for the essay I guess, but trust me I know.

Unfortunately for the users this is the easiest way, and it uses Microsoft software so no one can say anything about viruses etc... (including ms defender, with which I have a number of issues)

I will try and fix it for the next installer version xD

**Comment by DylDevs** [comment]
For now you can just install python and hit manually 👍

**Comment by Tumppi066** [comment]
Those will install automatically after Winget is downloaded

**Comment by DylDevs** [comment]
@Tumppi066 I think this issue should be closed.
