### ISSUE TITLE
Language settings other than English result in program loading time being too long and unresponsive（Ustawienia języka inne niż angielski powodują, że czas ładowania programu jest zbyt długi i nie reaguje）

### ISSUE THREAD

**Issue by nulijiazaizhong** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#202]
Non English language settings are slow to load and can easily cause processes to freeze and become unresponsive. It is recommended to add language packs to the program instead of calling Google Translate's API for on-site translation

Muiden kuin englanninkielisten asetusten lataaminen on hidasta, ja prosessit voivat helposti jäädyttää ja lopettaa vastaamisen. On suositeltavaa lisätä kielipaketteja ohjelmaan sen sijaan, että soittaisit Google Translaten API:lle paikan päällä tapahtuvaa kääntämistä varten.

**Comment by Cloud-121** [comment]
It should cache things, but yes, eventually, this will be added. Has been talked about for a while on the discord.

**Comment by Cloud-121** [comment]
> Adding a language pack is harder than it would seem. The app will cache the translations dynamically as they are called. So in the future the app will be just as fast as normal. 
> 
> Other problems that stem from the translations are incorrect word lengths causing a problem with readability.

Wouldn't the ui redesign make it easier? I thought react had a fancy thing for such thing

**Comment by Tumppi066** [comment]
Yup it does fix this, but for now this is a problem and there is pretty much nothing I can do in a timely manner 👍
