### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy'

### ISSUE THREAD

**Issue by dylanb92010** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#21]
Once I have installed ETS2 Lane assist using this video: https://youtu.be/Ssw2JlbthHw
I ran start.bat, and it opened cmd and gave me this:

  You can now view your Streamlit app in your browser.

  Local URL: (Hidden for privacy reasons)
  Network URL: (Hidden for privacy reasons)

pygame 2.3.0 (SDL 2.24.2, Python 3.10.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in thread Thread-3 (MainFileThread):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dylan\Documents\ETS Lane Assist\Euro-Truck-Simulator-2-Lane-Assist-main\AppUI.py", line 27, in MainFileThread
    import MainFile
  File "C:\Users\Dylan\Documents\ETS Lane Assist\Euro-Truck-Simulator-2-Lane-Assist-main\MainFile.py", line 49, in <module>
    import ets2LaneDetection as LaneDetection
  File "C:\Users\Dylan\Documents\ETS Lane Assist\Euro-Truck-Simulator-2-Lane-Assist-main\ets2LaneDetection.py", line 17, in <module>
    from ultrafastLaneDetector import UltrafastLaneDetector, ModelType
  File "C:\Users\Dylan\Documents\ETS Lane Assist\Euro-Truck-Simulator-2-Lane-Assist-main\ultrafastLaneDetector\__init__.py", line 1, in <module>
    from ultrafastLaneDetector.ultrafastLaneDetector import UltrafastLaneDetector, ModelType
  File "C:\Users\Dylan\Documents\ETS Lane Assist\Euro-Truck-Simulator-2-Lane-Assist-main\ultrafastLaneDetector\ultrafastLaneDetector.py", line 3, in <module>
    import scipy.special
ModuleNotFoundError: No module named 'scipy'

Any help to fix this issue would be appreciated, Thank you.

**Comment by Tumppi066** [comment]
This can simply be fixed by running 
> pip install scipy

But judging by that traceback, it seems that you are running python 3.10, that won't work right now. 

These instructions should get the app working (there are currently some bugs, and I don't have the time to fix them)

```
This will essentially clone the install I have.

Step 1. Uninstall your current python version (apps -> python -> uninstall)
Step 2. Download python 3.9.13 https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe
Step 3. Install some requirements by manually running commands in the terminal (to get correct versions)

pip install torch==1.13.1 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
pip install numpy==1.21.0 scipy==1.9.1


Step 4. Install the rest of the requirements (open the app location, click the file explorer address bar, type cmd.exe, pip install -r requirements.txt) 
```

After this you can follow the video tutorial on how to set it up in game. If this fixed it then be free to close the issue, otherwise I will try and answer again in a (relatively) timely fashion :D

**Comment by dylanb92010** [comment]
Thanks for the reply,
I followed all of those steps and fixed that issue. It seems that I have another problem.
When I run start.bat, it gives me this:

pygame 2.3.0 (SDL 2.24.2, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
←[92mSuccessfully loaded all settings ←[00m
Loaded model of size : 34
C:\Program Files\Python39\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Program Files\Python39\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
('setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.',)

After that, it continuously puts out the last line (('setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.',)). 
The preview windows comes up, but is grey and wont move. 

Any help would be appreciated, Thanks

**Comment by dylanb92010** [comment]
Thanks for the reply,
I followed all of those steps and fixed that issue. It seems that I have another problem.
When I run start.bat, it gives me this:

pygame 2.3.0 (SDL 2.24.2, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
←[92mSuccessfully loaded all settings ←[00m
Loaded model of size : 34
C:\Program Files\Python39\lib\site-packages\torchvision\models_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
warnings.warn(
C:\Program Files\Python39\lib\site-packages\torchvision\models_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=None.
warnings.warn(msg)
('setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.',)

After that, it continuously puts out the last line (('setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.',)).
The preview windows comes up, but is grey and wont move.

Any help would be appreciated, Thanks

**Comment by Tumppi066** [comment]
Hmm that's weird, it should've downloaded everything so that won't happen.
Paste this into a command line and tell me what it says. 

```
python 
import torch
import scipy
import numpy
print(scipy.__version__)
print(numpy.version.version)
print(torch.__version__)
```
![image](https://user-images.githubusercontent.com/83072683/230296401-ec218a12-ea6d-4bb0-9b72-e986bc5d4e3d.png)

**Comment by dylanb92010** [comment]
This is what happened after I entered all the commands:

>>> import torch
>>> import scipy
>>> import numpy
>>> print(scipy.__version__)
1.10.1
>>> print(numpy.version.version)
1.24.2
>>> print(torch.__version__)
2.0.0+cpu

**Comment by Tumppi066** [comment]
Did you install everything with my commands? Seems like your version are incorrect. 

You can reinstall them by doing
> pip uninstall scipy numpy torch

And then
> pip install torch==1.13.1 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
> pip install numpy==1.21.0 scipy==1.9.1

**Comment by dylanb92010** [comment]
After doing that I have some success, with 2 errors

After enabling preview , it recognizes my controller, it looked like it was fine until:

```
pygame 2.3.0 (SDL 2.24.2, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
←[92mSuccessfully loaded all settings ←[00m
Loaded model of size : 34
C:\Program Files\Python39\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Program Files\Python39\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
('Error(s) in loading state_dict for parsingNet:\n\tsize mismatch for cls.2.weight: copying a param with shape torch.Size([14472, 2048]) from checkpoint, the shape in current model is torch.Size([22624, 2048]).\n\tsize mismatch for cls.2.bias: copying a param with shape torch.Size([14472]) from checkpoint, the shape in current model is torch.Size([22624]).',)
←[93mDefault model not installed, please select one in the settings←[00m
```

If I enable Lane Assist it gives a second error:
`
("name 'lane_detector' is not defined",)`

Thanks for sticking with me as I have more and more errors :)

**Comment by Tumppi066** [comment]
Sorry for taking this long to answer... again ,_,
Anyway this error - ```("name 'lane_detector' is not defined",)``` - comes from the first one. 

But that is something I have never seen. It looks to be an error with the model file itself? Maybe try and redownload culane_34?

**Comment by dylanb92010** [comment]
Finally no errors!
When I run start.bat this is the output, which looks good except for the warnings that don't seem urgent:

```
pygame 2.3.0 (SDL 2.24.2, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
←[92mSuccessfully loaded all settings ←[00m
Loaded model of size : 34
C:\Program Files\Python39\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Program Files\Python39\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Right Indicator : 0
Left Indicator : 0
Enable/Disable Button : 17
Steering Axis : 0
Sensitivity : 500
Steering Offset : -150
Maximum Control : 0.2
Control Smoothness : 0
Disable Lane Assist When Indicating : True
Wheel : Controller (Wired Wheel)
←[92mController settings updated! ←[00m
```

The preview window is stuck at 0 FPS, bu it displays a picture instead of grey.
```
Specs:
CPU: Intel Core i3-9100
GPU: Intel Integrated
RAM: 8GB
```

**Comment by Tumppi066** [comment]
Ah... Ok at this point it's definitely your PC specs. The app really needs a GPU (specifically NVIDIA) to work properly. I have been working on CPU optimizations (right now I can run at around 20fps on my R7 5800x3d) but I don't think that is going to be enough in this case. Sorry ._.

I will close this with this comment... but if you want to ask anything else then go ahead, and I will answer (hopefully) in due time!

**Comment by dylanb92010** [comment]
> Ah... Ok at this point it's definitely your PC specs. The app really needs a GPU (specifically NVIDIA) to work properly. I have been working on CPU optimizations (right now I can run at around 20fps on my R7 5800x3d) but I don't think that is going to be enough in this case. Sorry ._.
> 
> I will close this with this comment... but if you want to ask anything else then go ahead, and I will answer (hopefully) in due time!

Thanks!
