### ISSUE TITLE
steering not working

### ISSUE THREAD

**Issue by Minion9113** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#22]
when the lane assist isnt started the capture is clean and running good but when im starting it it only is at 3 fps i have a i7 8700k and a gtx 1080!

**Comment by Tumppi066** [comment]
I'm guessing that it's running in cpu mode here. Can you screenshot the console when you open the application.

Sorry it took this long to respond; I was away from home over the weekend.

**Comment by Minion9113** [comment]
alr

**Comment by Minion9113** [comment]
![grafik](https://user-images.githubusercontent.com/91319585/230790996-b916042c-69de-4208-8b2a-480321754124.png)

**Comment by Tumppi066** [comment]
By the looks of things your torch is not the NVIDIA version. Also it seems that you are using python 3.11.3. That is too new, here are the instructions to essentially clone my install for it to work : 

```
This will essentially clone the install I have.

Step 1. Uninstall your current python version (apps -> python -> uninstall)
Step 2. Download python 3.9.13 https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe
Step 3. Install some requirements by manually running commands in the terminal (to get correct versions)

pip install torch==1.13.1 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
pip install numpy==1.21.0 scipy==1.9.1


Step 4. Install the rest of the requirements (open the app location, click the file explorer address bar, type cmd.exe, pip install -r requirements.txt) 
```

**Comment by Minion9113** [comment]
alright thanks dude

**Comment by Minion9113** [comment]
the capture works not but it doesnt steer. i have the controller as a second device like said in the readme.md

**Comment by Tumppi066** [comment]
Closed after such a long time.... 

In the future please use the anaconda-installer branch to install.
