### ISSUE TITLE
Logitech SDK support

### ISSUE THREAD

**Issue by michalkundrat** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#23]
Hey there, a long time ago I was working on a similar project to this myself. However, I was seriously struggling with any progress with the Logitech SDK. Would you please be able to give me any insight as to how you were able to get it to work with Python?
P.S. Yes, I am aware that it doesn't work in this project due to issues with program handles.

**Comment by michalkundrat** [comment]
Hey, thank you so much for giving me an answer despite it having been a while since you wrote the code.
I really do appreciate it!

**Comment by Tumppi066** [comment]
No worries, happy to help!
