### ISSUE TITLE
PC Specs 

### ISSUE THREAD

**Issue by dylanb92010** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#24]
I made [This Post](https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/issues/21) a while back. It was closed with PC Specs not being high enough to run this program. 

I have been thinking about building a PC with these specs:

```
> Intel Core i5 6500
> NVIDIA GTX 970
> 16GB RAM
```

Would this be enough to run this?

**Comment by Tumppi066** [comment]
My program uses mostly the cpu with the newest version. So when playing ETS2 at the same time it might still lag a bit... But it should be possible. 

Keep in mind that I haven't personally tested it with those specs so don't base your purchase decision on what I say :)

**Comment by dylanb92010** [comment]
I bought all the parts to build it and I will update you if I have any issues 
(Also, does this work with American Truck Simulator?)

**Comment by Tumppi066** [comment]
Great! Just remember to use the new installer from the anaconda installer branch.

As for ATS, the app supports any game that you can have two controllers at the same time, this is basically all the popular simulator games like BeamNG, ETS, ATS...

**Comment by dylanb92010** [comment]
Python has an issue
First, I open CMD and type` cd (location of updater.py) ` 
As showed in the tutorial video I typed `python updater.py `

I got this back:
`Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`


I tried opening updater.py in Python and got this:
```
'int' object is not subscriptable
←[91m Couldn't backup profiles←[00m
[Errno 2] No such file or directory: 'Euro-Truck-Simulator-2-Lane-Assist-main\\models'
←[91m Couldn't backup models←[00m
←[92m Old version removed←[00m
←[92m
 Downloading new version please wait...←[00m
←[92m Don't panic if it doesn't move, just wait.←[00m
←[94m
 100.0% 1288kb←[0m
←[92m Download complete←[00m
←[94m You can copy your profiles back into the app folder←[00m
←[92m Installing requirements...←[00m
←[92m 1 of 13←[00m
'pip' is not recognized as an internal or external command,
operable program or batch file.
 2 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 3 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 4 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 5 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 6 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 7 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 8 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 9 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 10 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 11 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 12 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 13 of 13
'pip' is not recognized as an internal or external command,
operable program or batch file.
 Installing torch for CPUs...
'pip' is not recognized as an internal or external command,
operable program or batch file.
 Everything is installed
```

I have no idea what else to try. 
I am running Python 3.9.13 as you suggested here: https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/issues/21#issuecomment-1497953789
Any help is appreciated.

**Comment by Tumppi066** [comment]
Try and use "python3" instead of python, that could fix the issue.

Also make sure that you tapped "add python to PATH" during installation.

**Comment by Tumppi066** [comment]
Also it seems that you are using the older installer, the new one can be downloaded here:
https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/archive/refs/heads/anaconda-updater.zip

**Comment by dylanb92010** [comment]
Its finally working!

![Screenshot 2023-06-05 002910](https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/assets/110776467/61f70a01-6047-4f6d-af19-324202dc69ec)

One more thing though, how do I configure this part of the settings?:

![image](https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/assets/110776467/73850cbf-9295-4543-b9a2-2b5bca3d6b98)

**Comment by Tumppi066** [comment]
Great news!

Those are button numbers, basically the index of the button you wan t to detect. The app should show the currently pressed buttons and you just add those numbers to their respective places. You don't need to touch steering axis.

Also if you do intend on using the "disable on indicating" then you will need to disable automatic indicator stopping in the settings.

**Comment by dylanb92010** [comment]
I don't know if I'm missing something, this is my fullscreen view of the program.
I don't see any place where it tells me the buttons I'm pressing.

![image](https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/assets/110776467/38321848-0db4-4bb7-bb10-bd7bf2fd9388)

**Comment by dylanb92010** [comment]
That works on my PS4 controller, but not my wheel.

**Comment by Tumppi066** [comment]
Hmm interesting, you could try and select the wheel, and the restart the app.

If that doesn't work then I think you'll just have to do it by trial and error ._.

**Comment by Tumppi066** [comment]
Based on that error message your steering axis is something other than zero.

It should be zero for basically every single controller.

**Comment by dylanb92010** [comment]
I have no more errors but I am confused on how to use it.
According to the [usage](https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#usage) tab, Im supposed to use this in game controller setup:
```
1: Keyboard + Xbox Controller
2: (My controller)
```
I just wanted to make sure that is correct.
Also, does this project still use ViGEM Bus Driver?

**Comment by dylanb92010** [comment]
Ok, so how do I use the lane assist.
When I toggle it, nothing happens when I start driving.

**Comment by Tumppi066** [comment]
Make sure that the steering axis is set to "controller 1" in the ets2 settings.

**Comment by dylanb92010** [comment]
I set all of the controls up and when I enable lane assist, the preview shows the lanes, but doesn't move the steer the truck at all

**Comment by dylanb92010** [comment]
I sent a request on Discord.

I got the lane assist to work on my PS4 Controller, I'm gonna do some fiddling with my wheel tomorrow and see if I can get that working.

Also, do you have any alternate downloads for the Tusimple-34 model? Ive been using culane-18 because I have issues with Onedrive downloads.

**Comment by Tumppi066** [comment]
Not sure if that request went through, clicked accept but still can't see you -_-

As long as you have LSTR enabled then the current "legacy" model doesn't matter.

**Comment by dylanb92010** [comment]
Do I have to disable Culane18?

**Comment by dylanb92010** [comment]
Which of the LSTR models should I be using? I looked in the models folder and there is 5 models.

**Comment by Tumppi066** [comment]
The default one is the best. I added all of them just in case :)

**Comment by dylanb92010** [comment]
The wheel still doesn't work. Is there a possibility that the steering axis isn't 0?

**Comment by Tumppi066** [comment]
We fixed this through discord, the steering axis indeed wasn't zero.
