### ISSUE TITLE
Missing The 'linux/input.h' - Windows

### ISSUE THREAD

**Issue by rknetwork** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#26]
I'm trying to run the newest v2.0-rewrite on Windows and apparently `evdev` requires `linux/input.h`

```
      The 'linux/input.h' and 'linux/input-event-codes.h' include files
      are missing. You will have to install the kernel header files in
      order to continue:
```

**Comment by Tumppi066** [comment]
That is a bug that I'll fix today, you can fix it by removing the 'app/plugins/EvdevControler' folder.

**Comment by Tumppi066** [comment]
This should now be solved in the newest update I did 👍

**Comment by rknetwork** [comment]
@Tumppi066 Thanks, but now the First Time Panel won't start:

```
[[94m0.031[0m] [[92msrc[93m\logger.py[0m]  - Logger initialized!
[[94m0.125[0m] [[92msrc[93m\settings.py[0m]        - ('Theme',)
[[94m0.344[0m] [[93mmain.py[0m]     - ("No module named 'evdev'",)
pygame 2.5.0 (SDL 2.28.0, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[94m0.531[0m] [[92msrc[93m\settings.py[0m]        - ('LSTRDrawLanes',)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Downloads\Euro-Truck-Simulator-2-Lane-Assist-2.0-rewrite\src\mainUI.py", line 59, in <lambda>
    helpers.MakeButton(pluginFrame, "First Time Setup", lambda: switchSelectedPlugin("plugins.FirstTimeSetup.main"), 2, 0, width=20, style="Accent.TButton")
  File "D:\Downloads\Euro-Truck-Simulator-2-Lane-Assist-2.0-rewrite\src\mainUI.py", line 127, in switchSelectedPlugin
    ui = plugin.UI(pluginFrame)
  File "D:\Downloads\Euro-Truck-Simulator-2-Lane-Assist-2.0-rewrite\plugins\FirstTimeSetup\main.py", line 47, in __init__
    self.page0()
  File "D:\Downloads\Euro-Truck-Simulator-2-Lane-Assist-2.0-rewrite\plugins\FirstTimeSetup\main.py", line 71, in page0
    self.logo = self.logo.resize((width, height), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by Tumppi066** [comment]
Have you tried restarting the app?

If so then do this.

**Installed with installer:** 
- Go into `~/venv/Scripts`
- Open a command prompt (click the file explorer address bar -> cmd.exe)
- Type `.\pip.exe uninstall pillow`
- Type `.\pip.exe install pillow`
- Try again

**Installed from source:**
- Open a command prompt (click the file explorer address bar -> cmd.exe)
- Type `.\pip.exe uninstall pillow`
- Type `.\pip.exe install pillow`

**Comment by rknetwork** [comment]
@Tumppi066 Same thing

**Comment by Tumppi066** [comment]
@rknetwork 

Ok that's interesting pillow really should be working. 
Can you run this command like you did the last ones?

`pip show pillow`

And then tell me the version.

**Comment by rknetwork** [comment]
@Tumppi066 Got it fixed:

Search and replace this:
`Image.ANTIALIAS`

with this:

`resample=Image.LANCZOS`

**Comment by Tumppi066** [comment]
Yup I for some reason your pillow doesn't include the default ANTIALIAS ._.

In any case good that you got it fixed, will add that to the FAQ on discord!

**Comment by rknetwork** [comment]
@Tumppi066 Also, I just wiped the whole thing and decided to start from scratch using installer, here is what was missing in vdev:

D:\Downloads\Euro-Truck-Simulator-2-Lane-Assist-anaconda-updater\venv\Scripts
```
pip install sv_ttk psutil pillow pygame cv2 opencv-python 
pip install dxcam onnx playsound mss pygments vgamepad wheel
pip install onnxruntime keyboard chlorophyll
```

**Comment by Tumppi066** [comment]
This is extremely weird since the installer should just get all of them from the requirements.txt file in the app folder.
I guess I should probably check my installer again xD

**Comment by rknetwork** [comment]
> This is extremely weird since the installer should just get all of them from the requirements.txt file in the app folder.
> I guess I should probably check my installer again xD

Yes, but when 1 package fails (evdev) - rest are ignored  😎

**Comment by Tumppi066** [comment]
Ah seems that I didn't push the changes yet xD 

I added a check for different systems so that it now doesn't do that xD

**Comment by rknetwork** [comment]
Anyways, I wasn't able to get it to work properly for weeks now, I tried both ETS2 and ATS, same result... Can you running it on a normal 1080p monitor with 1920x1080 resolution?

**Comment by Tumppi066** [comment]
What part exactly are you having issues with? And yes it should definitely work on a 1080p monitor :D 

1. The lanes detecting correctly
2. Setting up the app side of the input.
3. Setting up the game side of the input.
4. Inaccurate / "Bouncy" / Aggressive steering

**Comment by rknetwork** [comment]
> What part exactly are you having issues with? And yes it should definitely work on a 1080p monitor :D
> 
> 1. The lanes detecting correctly - NO
> 2. Setting up the app side of the input. - YES
> 3. Setting up the game side of the input. - YES
> 4. Inaccurate / "Bouncy" / Aggressive steering - YES

- The capturing camera is following the steering, when too close to the lane markings - it stops detecting lanes or detects wrong, this is when chaos begins

**Comment by Tumppi066** [comment]
Can you send me an image of what the app sees then? 
Preferably in a place where it doesn't detect them well and I'll check how it looks.

I'm using a different technique than UFLD called LSTR. It is much more prone to errors if the camera is not set just right. The flipside being it can run without a GPU. I could try and check v2 and see how well it runs and them might implement that as an option 👍

**Comment by rknetwork** [comment]
@Tumppi066 I will wait for the new version, I'm giving up on this one.
None of the lane recognition projects look promising at this point.

FYI: I found that CoordinateX,Y are being provided by the telemetry. Maybe it's worth comparing them to the GPS route and adjust steering accordingly. =)

**Comment by Tumppi066** [comment]
You can actually check how it should look and work here (though I had the sensitivity etc... wrong so it's bouncing)
https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/issues/25#issuecomment-1612848281

**Comment by Tumppi066** [comment]
Unfortunately I can't actually get the route from the game (well I get the start and end, but no the route itself) xD

I could do that otherwise 👍

**Comment by rknetwork** [comment]
> You can actually check how it should look and work here (though I had the sensitivity etc... wrong so it's bouncing) [#25 (comment)](https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/issues/25#issuecomment-1612848281)

I have tried every possible scenario, you know - I'm a maniac...

**Comment by rknetwork** [comment]
> Unfortunately I can't actually get the route from the game (well I get the start and end, but no the route itself) xD
> 
> I could do that otherwise 👍

The game does autosaves right, it should include the route. I'm still researching this

**Comment by Tumppi066** [comment]
@rknetwork 

That's actually genius. Want to come to a discord call tomorrow so I can get your lane assist fixed? I suddenly have an urge to get you onboard with developing some kind of route plugin xD. I already have access to the ETS2 API because of a plugin another person made

**Comment by rknetwork** [comment]
@Tumppi066 Let's hold off on this one for now... I lost my patience =))) I think I should write something in Rust hitting the memory directly...

**Comment by Tumppi066** [comment]
No worries! 

Tell me if you find something, I'm focusing on the tutorials for v2 xD

**Comment by Tumppi066** [comment]
Been a while so I will close this now regardless :)
