### ISSUE TITLE
session_start(): Failed to decode session object

### ISSUE THREAD

**Issue by rknetwork** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#32]
The sessions are working properly, readable and writeable.

When I first hit index.php - it creates session file under /tmp with this content:
` PMA_token | HMAC_secret |errors|`

When I hit login, it deletes the session file and throws this error:

```
phpMyAdmin - Error
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.
session_start(): Failed to decode session object. Session has been destroyed

```
phpMyAdmin 5.2.1
php83-8.3.0.a2
mysql80-server-8.0.32_3

No other errors are posted.

**Comment by Tumppi066** [comment]
I think this might've been the wrong repository :)

**Comment by rknetwork** [comment]
Oops

**Comment by Tumppi066** [comment]
No worries xD

You can close the issue so it doesn't clutter up the page 👍
