### ISSUE TITLE
ModuleNotFoundError: No module named 'vdf'

### ISSUE THREAD

**Issue by BoredKevin** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#76]
Hi, is it just me or for some reason ETS2 Lane Assist doesn't work when I launch it
I tried doing `pip install vdf` but nothing worked.

OS: Windows 11 22H2 Build 22621.2715
ETS2 Version: 1.49
Lane Assist Version: 1.6.0 7983911

If anyone knows how to fix this and get it working, it would be greatly appreciated. 😄 

![image](https://github.com/Tumppi066/Euro-Truck-Simulator-2-Lane-Assist/assets/107290249/0fe7b59d-0b40-4925-8ba2-67c07ad353fe)

**Comment by Cloud-121** [comment]
Hello, If you don't mind joining the [discord](https://discord.gg/qdehkSGN). We may be able to provide better support there

**Comment by BoredKevin** [comment]
Thank you for the fast reply. Sure, I'll check it out

**Comment by Tumppi066** [comment]
Closed as not active
